spring.application.name=estradao

spring.datasource.url=jdbc:postgresql://localhost:5433/estradao
spring.datasource.username=estradao
spring.datasource.password=estradao123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
